### ISSUE TITLE
Update spectral file generation script to SOCRATES2211

### ISSUE THREAD

**Issue by timlichtenberg** [FormingWorlds/AEOLUS#20]
Socrates 2211 has changed a few things in the spectral file scripting so that any spectral file generated with our current sp_gen_script will yield NaNs or errors.

Below are the differences in the spectral file generated by sp_gen_script.py with the same parameters as for our default sp_b318_HITRAN_a16 with the new Socrates version:

Block 0: Maximum number of spectral sub-bands in a band = 13480. This line is new.
Block 0: Number of continuum k-terms in a band: 18 instead of 1.
Block 2: Same stellar spectrum, different values beyond the 0.1 digit accuracy
Block 4: VERSION = 1 instead of 0
Block 4: Number of absorbers: 14 instead of 6 ; and overlap method = 0. The overlap method specification is new.
Block 5: additional k-terms, those already there are the same.
Block 18: number of active continua: 18 instead of 16. And more k-terms.
Block 19: more k-terms. Those already there are the same.

The resulting file from sp_gen_script.py can be seen here: https://github.com/FormingWorlds/AEOLUS/tree/modules/spectral_files/sp_b318_HITRAN_a16_SOCRATES2211/sp_b318_HITRAN_a16_Sun_t0_0Ga_claire_12 (The _k file was too large to push, I can share it in another way if needed)

The generation seems to produce good files, nothing strange in them that I can see so far. The soc_rad_conv output is what is affected
For instance, the output from the default file (the one used for the past 2ish years) with my parameters is below:

Calculate mixing ratios from partial pressures.
P_surf: 101900.0
p_i: {'H2O': 400.0, 'NH3': 0.0, 'CO2': 3500.0, 'CH4': 0.0, 'CO': 0.0, 'O2': 20000.0, 'N2': 78000.0, 'H2': 0.0}
x_i: {'H2O': 0.003925417075564278, 'NH3': 0.0, 'CO2': 0.03434739941118744, 'CH4': 0.0, 'CO': 0.0, 'O2': 0.19627085377821393, 'N2': 0.7654563297350343, 'H2': 0.0}
/home/x_ryabo/socrates_2211/socrates_main/sbin/Cl_run_cdf: line 144: [: 3181: integer expression expected
Mapping sub-bands to channels.
/home/x_ryabo/socrates_2211/socrates_main/sbin/Cl_run_cdf: line 144: [: 3181: integer expression expected
Mapping sub-bands to channels.
w/o stratosphere (net, OLR): 202.757 202.757 W/m^2
26.272220611572266

New file generated with Socrates 2211:

Calculate mixing ratios from partial pressures.
P_surf: 101900.0
p_i: {'H2O': 400.0, 'NH3': 0.0, 'CO2': 3500.0, 'CH4': 0.0, 'CO': 0.0, 'O2': 20000.0, 'N2': 78000.0, 'H2': 0.0}
x_i: {'H2O': 0.003925417075564278, 'NH3': 0.0, 'CO2': 0.03434739941118744, 'CH4': 0.0, 'CO': 0.0, 'O2': 0.19627085377821393, 'N2': 0.7654563297350343, 'H2': 0.0}
/home/x_ryabo/socrates_2211/socrates_main/sbin/Cl_run_cdf: line 144: [: 3181: integer expression expected
Mapping sub-bands to channels.
/home/x_ryabo/socrates_2211/socrates_main/sbin/Cl_run_cdf: line 144: [: 3181: integer expression expected
Mapping sub-bands to channels.
w/o stratosphere (net, OLR): nan nan W/m^2
621.7962238788605

**Comment by Ryan-Boukrouche** [comment]
Thanks, I think I tried deleting #19 a while ago but it didn't work.
This is in progress, James Manners is helping in this.

**Comment by timlichtenberg** [comment]
Yes, I was just linking the two, your information on the bands up there is very helpful! :-)

**Comment by timlichtenberg** [comment]
I think we've now managed to produce enough reasonable new spectral files with SOCRATES 2211 and 2306, so that this and issue #19 can be closed. @Ryan-Boukrouche and @nichollsh, agree?

**Comment by Ryan-Boukrouche** [comment]
Did you say that the current sp file generation script requires Socrates version 2211 or earlier?

**Comment by timlichtenberg** [comment]
No it should work with all recent SOCRATES versions, at least it does for me and Harrison; could you try update the code to the latest `master` version and re-run the simulation you have been doing? You can also choose a different spectral file from here: https://drive.google.com/drive/folders/1mgML9f7AhdMXbFJRdasopgejie_ZBRyO?usp=drive_link. Let us know in Discord if that doesn't work. :-)
