### ISSUE TITLE
Instellation array becomes zero with increased surface pressure

### ISSUE THREAD

**Issue by Ryan-Boukrouche** [FormingWorlds/AEOLUS#27]
With the current master branch of AEOLUS and with the following changes:
- Uncommented the call to plot_flux_balance() in radcoupler.py
- Imported the module plot_flux_balance in radcoupler.py
- Updated the import of General_Adiabat in plot_flux_balance.py

With a surface pressure of 1 bar and roughly Earth composition:
 vol_partial    = { 
                          "H2O" :  0.004e5,
                          "NH3" :  0.,
                          "CO2" :  0.035e5,
                          "CH4" :  0.,
                          "CO"  :  0.,
                          "O2"  :  0.20e5,
                          "N2"  :  0.78e5,
                          "H2"  :  0.
                        }

The output instellation flux array is behaving correctly:

Instellation flux array =  [638.9341  638.9336  638.9331  638.9328  638.9322  638.9316  638.93085
 638.9303  638.9294  638.9287  638.9277  638.92664 638.92535 638.9243
 638.92285 638.92126 638.91986 638.9182  638.91626 638.91394 638.9118
 638.9091  638.9061  638.9032  638.89984 638.89606 638.8919  638.8876
 638.88257 638.8773  638.87146 638.8651  638.858   638.85016 638.8416
 638.8323  638.82196 638.81085 638.7985  638.7849  638.77045 638.7539
 638.73596 638.7164  638.6951  638.6718  638.64575 638.61194 638.57465
 638.5323  638.4837  638.426   638.3578  638.2796  638.19055 638.0868
 637.97046 637.8406  637.684   637.49255 637.264   637.0046  636.7256
 636.4364  636.13446 635.81104 635.4487  635.03107 634.5473  633.9919
 633.3543  632.64453 631.88837 631.0884  630.2443  629.3512  628.3969
 627.37177 626.2685  625.0795  623.7749  622.374   620.83057 619.12274
 617.20404 615.00995 612.46436 609.4682  605.88293 601.52094 596.2214
 589.8904  582.4302  573.69165 563.8376  553.1511  542.9461  533.37866
 523.9332  514.3712  504.56683]

and the output graph from plot_flux_balance is attached as "TP_0_1bar_Earth.pdf" :
[TP_0_1bar_Earth.pdf](https://github.com/FormingWorlds/AEOLUS/files/11622998/TP_0_1bar_Earth.pdf)

With a surface pressure of 10 bar and keeping the same proportions:

 vol_partial    = { 
                          "H2O" :  0.004e6,
                          "NH3" :  0.,
                          "CO2" :  0.035e6,
                          "CH4" :  0.,
                          "CO"  :  0.,
                          "O2"  :  0.20e6,
                          "N2"  :  0.78e6,
                          "H2"  :  0.
                        }

The output instellation flux array is now zero:

Instellation flux array =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]

The output graph from plot_flux_balance is attached as "TP_0_10bar_Earth.pdf" :
 [TP_0_10bar_Earth.pdf](https://github.com/FormingWorlds/AEOLUS/files/11623063/TP_0_10bar_Earth.pdf)

**Comment by Ryan-Boukrouche** [comment]
Update:

This issue seems due to H2O. This is the threshold I've currently reached: 

vol_partial    = { 
                          "H2O" :  0.003582e6,
                          "NH3" :  0.0,
                          "CO2" :  0.035e6,
                          "CH4" :  0.0,
                          "CO"  :  0.0,
                          "O2"  :  0.20e6,
                          "N2"  :  0.78e6,
                          "H2"  :  0.0
                        }

Still a surface pressure of about 10bar (10.18582 bar to be exact), but if we keep a partial pressure of H2O at 0.003582e6 (about 3.517% mixing ratio) the instellation array is still correct.

Setting H2O to 0.003583e6 makes the instellation array go to zero...

**Comment by nichollsh** [comment]
I am seeing the same bug with the instellation array `atm.SW_flux_down` go to zero with the same configuration as yours. The plot below shows the result with your first 10 bar case:
```
vol_partial = {
        "H2O" : 0.004e6,
        "NH3" : 0.,
        "CO2" : 0.035e6,
        "CH4" : 0.,
        "CO" : 0.,
        "O2" : 0.20e6,
        "N2" : 0.78e6,
        "H2" : 0.
        }
T_surf = 298.0  # Guessed from your plots
trppT = 30.0    # ^^
P_top = 10.0    # ^^

```


![Image](https://github.com/FormingWorlds/AEOLUS/assets/32022679/82a7cdb5-f2e3-48aa-9f87-c3c8cd7338e9)


With a surface temperature of increased 305 K (increased from 298 K), the bug doesn't appear for H2O partial surface pressures of 0.003583e6 Pa and 0.003582e6 Pa.

It seems that bug is a function of both surface temperature and H2O partial pressure. Since the water is sat on its saturation pressure curve the whole time, maybe it's a case of H20 condensation? At 298 K, the saturation vapour pressure for water is 0.00314e6 Pa*, which is suspiciously close to the pressures you mentioned (given that I guessed your T_surf anyway).


I don't think it's indirectly the aloft conditions that are the issue, even though it's the downward stream that's affected. Playing with `P_top` and `trppT` doesn't seem to make a difference.

* https://www.engineeringtoolbox.com/water-vapor-saturation-pressure-d_599.html

**Comment by nichollsh** [comment]
That being said, the mass mixing ratio of water hardly differs between the working and not-working cases, so I don't know why exactly it would impact the RT so significantly.
