### ISSUE TITLE
Saturation vapor pressure of water is inaccurate for T > 350 K

### ISSUE THREAD

**Issue by Nicholaswogan** [FormingWorlds/AEOLUS#28]
I have noticed some differences between `GeneralAdiabat.py` in AEOLUS and my model, [`clima`](https://github.com/Nicholaswogan/clima), for hot atmospheres (T ~ 400 K). It looks like the saturation vapor pressure of H2O in AEOLUS might be the reason. In the `GeneralAdiabat.py` function, I use the `p_sat` function to compute saturation vapor pressure of H2O at 400 K to be 3.215963 bar. But [this website](https://www.engineeringtoolbox.com/water-vapor-saturation-pressure-d_599.html) says the saturation vapor pressure at 400 K is 2.45 bar. This is a big difference for warm steam-dominated atmospheres.

The attached plot compares the Engineering ToolBox saturation vapor pressure to the `p_sat` function in `GeneralAdiabat.py`. `GeneralAdiabat.py` seems to over-predict saturation vapor pressure for T > 350 K. 

![sat_vapor_pressure_comparison](https://github.com/FormingWorlds/AEOLUS/assets/18489667/1866bba1-3f82-4069-8928-15940b2f5a7b)

**Comment by timlichtenberg** [comment]
Hi @Nicholaswogan! Thanks for notifying us, I'll get back to this asap. Also pinging @arejaygraham and @Ryan-Boukrouche.

**Comment by Nicholaswogan** [comment]
Hi Tim! No problem. 

It looks like `GeneralAdiabat.py` relies on a temperature-constant latent heat in order to compute the saturation vapor pressure (via Clausius-Clapeyron). `GeneralAdiabat.py` uses the T = 274 K latent heat of vaporization for all temperatures, so this is why our saturation vapor pressures differ for T = 400 K.

In `clima`, I allow latent heat to be linear as a function of temperature, with a step-change at the critical point. This isn't a perfect representation, but I think is a bit more accurate for steam-rich warm atmospheres.

**Comment by hinnes97** [comment]
@timlichtenberg  For my work on Hycean worlds I implemented a lookup table based on IAPWS (Wagner & Pruß 2002) for the properties of water relevant to calculating moist adiabats (p_sat, L and dln p_sat/dln T) for use between the triple point and the critical point. Happy to look at putting this into AEOLUS, I already have the data sitting there in my Fortran file

**Comment by timlichtenberg** [comment]
@hinnes97 That would be amazing of course! :-)

**Comment by timlichtenberg** [comment]
@hinnes97 Thanks a lot, seems to work like a charm. :)
@Nicholaswogan Did this solve the issue for you?
